---
"$schema": https://github.com/hyperledger-labs/fablo/releases/download/1.2.0/schema.json
global:
  fabricVersion: 2.5.4
  tls: true
  engine: docker
  peerDevMode: false
orgs:
  - organization:
      name: Orderer
      domain: orderer.example.com
    orderers:
      - groupName: group1
        type: solo
        instances: 1
    tools:
      fabloRest: true
  - organization:
      name: Voter
      domain: voter.example.com
    peer:
      instances: 2 # This value has to match 'channels.orgs.peers' value.
      db: LevelDb
    tools:
      fabloRest: true
      explorer: true
channels:
  - name: vote-channel
    orgs:
      - name: Voter
        peers: # This value has to match 'orgs.peer.instances' value.
          - peer0 # MUST have 'peer0' as the first peer for 'explorer' to work.
          - peer1
         #- peer2
         #- peer3
         #- peer4
         #- peer5
         #- peer6
         #- peer7
chaincodes:
  - name: chaincode_vote
    version: 0.0.1
    lang: golang
    channel: vote-channel
    directory: "./chaincode"
    privateData:
      - name: collection_public_keys
        orgNames:
            - Voter
  - name: chaincode_public_keys
    version: 0.0.1
    lang: golang
    channel: vote-channel
    directory: "./chaincode"