---
"$schema": https://github.com/hyperledger-labs/fablo/releases/download/1.2.0/schema.json
global:
  fabricVersion: 2.5.4
  tls: true
  engine: docker
  peerDevMode: false
orgs:
  - organization:
      name: Orderer
      domain: orderer.example.com
    orderers:
      - groupName: group1
        type: solo
        instances: 1
    tools:
      fabloRest: true
  - organization:
      name: Org1
      domain: org1.example.com
    peer:
      instances: 2
      db: LevelDb
    tools:
      fabloRest: true
      explorer: true
channels:
  - name: my-channel1
    orgs:
      - name: Org1
        peers:
          - peer0
          - peer1
chaincodes:
  - name: chaincode1
    version: 0.0.1
    lang: node
    channel: my-channel1
    directory: "./chaincode/chaincode-kv-node"
